version: '3.9'

services:
  hacklights-db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  hacklights-web:
    build: 
      context: backend
      dockerfile: backend.Dockerfile
    volumes: 
      - ./backend:/opt/app
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - hacklights-db
